import { Imovel, Documento, Usuario } from '@/types/imob'

// Usuários das famílias (para isolamento simulado e consistente com RLS Supabase)
export const USUARIOS_INICIAIS: Usuario[] = [
  {
    id: 'usr-1',
    nome: 'Ana Silveira',
    email: 'operacao@mfo.com.br',
    cargo: 'Analista de Operações MFO',
    familia_id: 'fam-oliveira',
    familia_nome: 'Família Oliveira & Associados',
    avatar_url: 'https://img.usecurling.com/ppl/medium?gender=female&seed=28',
  },
  {
    id: 'usr-2',
    nome: 'Carlos Mendes',
    email: 'gestor@mfo.com.br',
    cargo: 'Gestor Patrimonial',
    familia_id: 'fam-braganca',
    familia_nome: 'Família Bragança',
    avatar_url: 'https://img.usecurling.com/ppl/medium?gender=male&seed=42',
  },
]

export const IMOVEIS_INICIAIS: Imovel[] = [
  {
    id: 'imv-1',
    familia_id: 'fam-oliveira',
    nome: 'Edifício Boulevard Jardins - Conjunto 1402',
    endereco: 'Alameda Lorena, 1420, Conjunto 1402, Jardins, São Paulo - SP',
    situacao: 'ocupado',
    matricula: '128.945 - 4º CRI de São Paulo',
    observacoes: 'Contrato de locação comercial vigente até Novembro/2026. Seguro predial em dia.',
    documento_principal_id: 'doc-1',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-04-10T14:30:00Z',
  },
  {
    id: 'imv-2',
    familia_id: 'fam-oliveira',
    nome: 'Mansão Alphaville Residencial 2',
    endereco: 'Alameda das Bromélias, 210, Alphaville, Santana de Parnaíba - SP',
    situacao: 'desocupado',
    matricula: '54.210 - CRI de Barueri',
    observacoes:
      'Imóvel desocupado para visitas. Chaves sob responsabilidade da portaria e zeladoria.',
    documento_principal_id: 'doc-3',
    created_at: '2024-02-01T11:20:00Z',
    updated_at: '2024-04-12T09:15:00Z',
  },
  {
    id: 'imv-3',
    familia_id: 'fam-oliveira',
    nome: 'Galpão Logístico Tamboré Módulo 04',
    endereco: 'Avenida Marcos Penteado de Ulhôa Rodrigues, 3800, Tamboré, Barueri - SP',
    situacao: 'em_reforma',
    matricula: '89.112 - CRI de Barueri',
    observacoes: 'Reforma do piso industrial e substituição de luminárias LED em andamento.',
    documento_principal_id: 'doc-5',
    created_at: '2024-02-18T16:00:00Z',
    updated_at: '2024-04-05T17:00:00Z',
  },
  {
    id: 'imv-4',
    familia_id: 'fam-oliveira',
    nome: 'Apartamento Duplex Leblon Vista Mar',
    endereco: 'Avenida Delfim Moreira, 890, Apto 1201, Leblon, Rio de Janeiro - RJ',
    situacao: 'ocupado',
    matricula: '44.301 - 2º RGI do Rio de Janeiro',
    observacoes: 'Uso exclusivo pelos membros da família durante a temporada de inverno.',
    documento_principal_id: 'doc-7',
    created_at: '2024-03-01T08:30:00Z',
    updated_at: '2024-04-14T11:45:00Z',
  },
  {
    id: 'imv-5',
    familia_id: 'fam-oliveira',
    nome: 'Terreno Fazenda Boa Vista - Gleba C',
    endereco: 'Rodovia Castelo Branco, km 102, Fazenda Boa Vista, Porto Feliz - SP',
    situacao: 'indisponivel',
    matricula: '22.908 - CRI de Porto Feliz',
    observacoes: 'Processo de regularização de fração ideal e unificação de matrícula em cartório.',
    documento_principal_id: undefined,
    created_at: '2024-03-20T13:00:00Z',
    updated_at: '2024-04-02T15:10:00Z',
  },
  // Imóvel de outra família (para validação do RLS na interface)
  {
    id: 'imv-6',
    familia_id: 'fam-braganca',
    nome: 'Cobertura Morumbi Panamby',
    endereco: 'Rua Deputado Laércio Corte, 1500, Panamby, São Paulo - SP',
    situacao: 'ocupado',
    matricula: '19.450 - 11º CRI SP',
    observacoes: 'Propriedade da Família Bragança.',
    documento_principal_id: 'doc-8',
    created_at: '2024-01-10T10:00:00Z',
    updated_at: '2024-03-01T10:00:00Z',
  },
]

export const DOCUMENTOS_INICIAIS: Documento[] = [
  {
    id: 'doc-1',
    familia_id: 'fam-oliveira',
    imovel_id: 'imv-1',
    nome: 'Escritura Definitiva Registrada - Boulevard Jardins.pdf',
    tipo: 'documento_principal',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    tamanho_formatado: '3.4 MB',
    tamanho_bytes: 3565158,
    data_documento: '2022-06-18',
    descricao: 'Escritura pública lavrada no 14º Cartório de Notas e averbada na matrícula.',
    is_principal: true,
    created_at: '2024-01-15T10:05:00Z',
  },
  {
    id: 'doc-2',
    familia_id: 'fam-oliveira',
    imovel_id: 'imv-1',
    nome: 'Contrato de Locação Comercial - TechCorp Brasil.pdf',
    tipo: 'contrato_locacao',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    tamanho_formatado: '1.8 MB',
    tamanho_bytes: 1887436,
    data_documento: '2023-11-01',
    descricao: 'Contrato com fiador e seguro fiança Porto Seguro.',
    is_principal: false,
    created_at: '2024-01-16T14:20:00Z',
  },
  {
    id: 'doc-3',
    familia_id: 'fam-oliveira',
    imovel_id: 'imv-2',
    nome: 'Certidão de Matrícula Atualizada com Ônus.pdf',
    tipo: 'documento_principal',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    tamanho_formatado: '2.1 MB',
    tamanho_bytes: 2202009,
    data_documento: '2024-01-10',
    descricao: 'Certidão vintenária negativa emitida pelo CRI Barueri.',
    is_principal: true,
    created_at: '2024-02-01T11:25:00Z',
  },
  {
    id: 'doc-4',
    familia_id: 'fam-oliveira',
    imovel_id: 'imv-2',
    nome: 'Carnê IPTU 2025 - Cota Única Paga.pdf',
    tipo: 'iptu',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    tamanho_formatado: '650 KB',
    tamanho_bytes: 665600,
    data_documento: '2025-01-20',
    descricao: 'Comprovante de quitação anual de IPTU com desconto de 7%.',
    is_principal: false,
    created_at: '2025-01-25T09:10:00Z',
  },
  {
    id: 'doc-5',
    familia_id: 'fam-oliveira',
    imovel_id: 'imv-3',
    nome: 'Memorial Descritivo e Planta Arquitetônica.pdf',
    tipo: 'documento_principal',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    tamanho_formatado: '8.7 MB',
    tamanho_bytes: 9122611,
    data_documento: '2021-09-14',
    descricao: 'Projeto executivo com especificações de piso para 6 ton/m² e docas.',
    is_principal: true,
    created_at: '2024-02-18T16:05:00Z',
  },
  {
    id: 'doc-6',
    familia_id: 'fam-oliveira',
    imovel_id: 'imv-3',
    nome: 'Contrato de Empreitada Reforma do Galpão.pdf',
    tipo: 'outros',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    tamanho_formatado: '1.2 MB',
    tamanho_bytes: 1258291,
    data_documento: '2024-03-01',
    descricao: 'Contrato com a construtora Alpha Engenharia.',
    is_principal: false,
    created_at: '2024-03-05T10:40:00Z',
  },
  {
    id: 'doc-7',
    familia_id: 'fam-oliveira',
    imovel_id: 'imv-4',
    nome: 'Escritura Pública de Compra e Venda - Leblon.pdf',
    tipo: 'documento_principal',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    tamanho_formatado: '4.5 MB',
    tamanho_bytes: 4718592,
    data_documento: '2020-04-15',
    descricao: 'Cópia autenticada com quitação de ITBI e certidões cíveis.',
    is_principal: true,
    created_at: '2024-03-01T08:35:00Z',
  },
  {
    id: 'doc-8',
    familia_id: 'fam-braganca',
    imovel_id: 'imv-6',
    nome: 'Escritura Cobertura Panamby.pdf',
    tipo: 'documento_principal',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    tamanho_formatado: '3.0 MB',
    tamanho_bytes: 3145728,
    data_documento: '2019-08-10',
    descricao: 'Escritura da Família Bragança',
    is_principal: true,
    created_at: '2024-01-10T10:05:00Z',
  },
]
